#!/bin/bash
# Copyright 2013 Johan Rydberg.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DOCKER_OPTIONS=${DOCKER_OPTIONS:-}

prog_name=$0
manifest=".travis-ci.yml"

if ! [ -e $manifest ]; then
  echo "$prog_name: $manifest: no such file"
  exit 1
fi

tar -c .|docker $DOCKER_OPTIONS run -rm -i -a stdout -a stderr -a stdin jrydberg/travis-build /bin/bash -c "mkdir -p /data && cd /data && tar -xC /data && /build/build"
