#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
rm -rf /var/lib/apt/lists/*
apt-get clean
